[project]
name = "transcription-audio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.13.0",
    "datasets[audio]>=4.8.4",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "soundfile>=0.13.1",
    "torch>=2.11.0",
    # "transformers @ git+https://github.com/nyrahealth/transformers.git@crisper_whisper",
    "batchalign>=0.8.2.post13",
]
