[project]
name = "vllm"
version = "0.1.0"
description = "Runs vLLM"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.13.0",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "soundfile>=0.13.1",
    "httpx>=0.28.1",
    "openai>=2.32.0",
    # "vllm>=0.19; platform_machine != 'arm64'",
]

[dependency-groups]
cuda = [
    "nvidia-cudnn-cu12; platform_machine != 'arm64'",
    "nvidia-cublas-cu12; platform_machine != 'arm64'",
    "nvidia-nccl-cu12; platform_machine != 'arm64'",
    "nvidia-cuda-runtime-cu12; platform_machine != 'arm64'",
]

test = [
    "pytest>=7.0.0",
]

[tool.uv]
default-groups = []
environments = [
    "platform_machine != 'arm64'",
    "sys_platform == 'darwin' and platform_machine == 'arm64'",
]